sudo: required

language: generic

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sh travis.sh

env:
  global:
    - DOCKER_USERNAME=livegrepbuild
    - secure: "hguhUWLxcX1jYRu+ODh3SLzRVzgjVp2sJIaVpaipAuwyUtwXL9J071huZFuF5MG3iha/Ek9gWvxiiHoCq9xz0C9Ul1y/R0FHYyhwTm7x93w7HlAXF0u8OpC+gftY88O60xNkMoy3g1BMJmIDyF25ulLx1ndK7TkrWiRkworQwRUFz0IhtCrRQkWObo2QpXBneQtZNYfoWUsU/FzTjuPyieMHEUF+R2M89KW51P3lshZNQsjMNILi46yTbpkXMt0iNUGVgRdCYN86a3uPmIcO7HIFye3VlpN3fM30XvHR2WMLYiO1goBrZ6ZTcFuZne0Qn10NO/WJDlzsTgIEQxi11YCD7dj3pSfYTkVZnnnYAxhxIjkgYqU2mcsKQX46oHtiW6rae+IlphQhWkoC2jZjGFULQmddMahHHS3YXVcpUOwPhcz8EE2bDhdVEfr0/JS/15pxN029Izlyqw0+1uoAAanNtRfM7SYD7U9PGG7YkLs0HRYA4Le2sLc1hlaNwHXvk8VHBKwCWs1l7m5jvT5l+cXcZimthR+mRGq9Pt6clQYpSNQEpY5TQJIN/rdc0HYLJDilfkeFBxDqA6tY5iHX2+pJBabkJoA9SOwNjBCt5/+KS7Az6ds4pnJ9QAc8EZb3UHbpiJplhOR679B3NqriZsZht7gKB5nBr8dybA7TrNs="
